name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build-docker-image:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Login to Github Container Registry
      uses: docker/login-action@v3
      with: 
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - name: "Build Container Image"
      run: |
        docker build . --tag ghcr.io/castelshal/argus:latest
        docker push ghcr.io/castelshal/argus:latest
        
      
